# Generated by Django 5.0.1 on 2024-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savouge', '0003_alter_company_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='name',
            field=models.TextField(),
        ),
    ]
