# Generated by Django 5.0.1 on 2024-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savouge', '0004_alter_company_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
